version: '0.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: joxmal
      POSTGRES_PASSWORD: 2288
      POSTGRES_DB: nestdb
    ports:
      - "5498:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - db